import { Router } from 'express';
import interfacesRouter from './interfaces';
import modelsRouter from './models';
import mappingsRouter from './mappings';
import graphRouter from './graph';
import statsRouter from './stats';
import mockRouter from './mock';
import importRouter from './import';
import parserRouter from './parser';
import docsRouter from './docs';
import performanceRouter from './performance';
import openapiRouter from './openapi';
import projectsRouter from './projects';
import approvalsRouter from './approvals';
import notificationsRouter from './notifications';
import webhooksRouter from './webhooks';
import backupRouter from './backup';
import tracingRouter from './tracing';
import cicdRouter from './cicd';
import dataSimulatorRouter from './dataSimulator';
import projectParserRouter from './projectParser';
import dataSourceRouter from './dataSource';
import realtimeRouter from './realtime';
import supabaseRouter from './supabase';
import teableRouter from './teable';
import testSuiteRouter from './testSuite';
import diffRouter from './diff';
import grpcRouter from './grpc';
import workflowRouter from './workflow';
import aiRouter from './ai';
import sdkGeneratorRouter from './sdkGenerator';
import gatewayRouter from './gateway';
import environmentsRouter from './environments';
import rateLimitRouter from './rateLimit';
import monitoringRouter from './monitoring';
import marketplaceRouter from './marketplace';
import i18nRouter from './i18n';

const router = Router();

router.use('/interfaces', interfacesRouter);
router.use('/models', modelsRouter);
router.use('/mappings', mappingsRouter);
router.use('/graph', graphRouter);
router.use('/stats', statsRouter);
router.use('/mock', mockRouter);
router.use('/import', importRouter);
router.use('/parser', parserRouter);
router.use('/docs', docsRouter);
router.use('/performance', performanceRouter);
router.use('/openapi', openapiRouter);
router.use('/projects', projectsRouter);
router.use('/approvals', approvalsRouter);
router.use('/notifications', notificationsRouter);
router.use('/webhooks', webhooksRouter);
router.use('/backup', backupRouter);
router.use('/tracing', tracingRouter);
router.use('/cicd', cicdRouter);
router.use('/data-simulator', dataSimulatorRouter);
router.use('/project-parser', projectParserRouter);
router.use('/data-source', dataSourceRouter);
router.use('/realtime', realtimeRouter);
router.use('/supabase', supabaseRouter);
router.use('/teable', teableRouter);
router.use('/diff', diffRouter);
router.use('/grpc', grpcRouter);
router.use('/workflow', workflowRouter);
router.use('/ai', aiRouter);
router.use('/sdk-generator', sdkGeneratorRouter);
router.use('/gateway', gatewayRouter);
router.use('/environments', environmentsRouter);
router.use('/rate-limit', rateLimitRouter);
router.use('/monitoring', monitoringRouter);
router.use('/marketplace', marketplaceRouter);
router.use('/i18n', i18nRouter);
router.use('/test-suite', testSuiteRouter);

export default router;
